#!/bin/sh

usage() {
    echo "usage: $(basename "$0") [OPTIONS...] APPYML VERSION

Options:
    --no-commit                Do not commit change.

Arguments:
    APPYML                     Path to the application's definitions YML file.
    VERSION                    Version of the baseimage (e.g. 2.0.0).
"
}

die() {
    [ -z "$*" ] || echo "ERROR: $*"
    exit 1
}

die_usage() {
    [ -z "$*" ] || echo "ERROR: $*"
    echo
    usage
    exit 1
}

promptyn() {
    echo -n "$1 (y/n)?"
    old_stty_cfg=$(stty -g)
    stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg
    echo
    echo "$answer" | grep -iq "^y"
}

APPYML=
VERSION=
DO_COMMIT=true

# Parse arguments.
while [ $# -ne 0 ]
do
    case "$1" in
        --no-commit)
            DO_COMMIT=false
            ;;
        -h|--help)
            die_usage
            ;;
        -*)
            die_usage "Unknown option: $1"
            ;;
        *)
            if [ -z "$APPYML" ]; then
                APPYML="$1"
            elif [ -z "$VERSION" ]; then
                VERSION="$1"
            else
                die_usage "Unknown argument: $1"
            fi
    esac
    shift
done

# Validate arguments.
[ -n "$APPYML" ] || die_usage "Application's definitions YML file is missing."
[ -f "$APPYML" ] || die_usage "File not found: '$APPYML'"
[ -n "$VERSION" ] || die_usage "Version is missing."

APPDIR="$(readlink -f "$(dirname "$APPYML")")"

[ -f "$APPDIR"/Dockerfile ] || die_usage "File not found: '"$APPDIR"/Dockerfile'."

if grep -q "^FROM jlesage/baseimage.*-v$VERSION\$" "$APPDIR"/Dockerfile; then
    echo "Baseimage version already set to $VERSION."
    exit 0
fi

# Modify baseimage version in Dockerfile.
sed -i.bak "s|\(^FROM jlesage/baseimage.*-v\)\([0-9]\+\.[0-9]\+\.[0-9]\+\)$|\1$VERSION|" "$APPDIR"/Dockerfile
diff "$APPDIR"/Dockerfile "$APPDIR"/Dockerfile.bak > /dev/null
if [ "$?" -ne 1 ]; then
    die "Failed to set baseimage to version '$VERSION'."
fi
rm "$APPDIR"/Dockerfile.bak

# Commit changes.
if $DO_COMMIT && [ -d "$APPDIR"/.git ]; then
    echo "The following changes will be applied:"
    git -C "$APPDIR" --no-pager diff Dockerfile
    if promptyn 'Proceed'; then
        git -C "$APPDIR" add Dockerfile
        git -C "$APPDIR" commit -m "Upgraded baseimage to version $VERSION."
    else
        exit 1
    fi
fi
