#!/bin/sh

SCRIPTDIR="$(readlink -f "$(dirname "$0")")"

usage() {
    echo "usage: $(basename "$0") APPYML CHANGE [CHANGE...]

Arguments:
    APPYML                     Path to the application's definitions YAML file.
    CHANGE                     Change to be added in the changelog.  Prepend
                               with 'XX:' to set the level.
"
}

die() {
    [ -z "$*" ] || echo "ERROR: $*"
    exit 1
}

die_usage() {
    [ -z "$*" ] || echo "ERROR: $*"
    echo
    usage
    exit 1
}

promptyn() {
    echo -n "$1 (y/n)?"
    old_stty_cfg=$(stty -g)
    stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg
    echo
    echo "$answer" | grep -iq "^y"
}

APPYML="$1"

# Validate arguments.
[ -n "$APPYML" ] || die_usage "Application's definitions YAML file is missing."
[ -f "$APPYML" ] || die_usage "File not found: '$APPYML'"
[ -n "$2" ] || die_usage "At least one change is needed."

shift 1

APPDIR="$(readlink -f "$(dirname "$APPYML")")"
APPFILE="$(basename "$APPYML")"

# Make sure the definitions file is not already modified.
if [ -d "$APPDIR"/.git ] && [ -n "$(git -C "$APPDIR" diff "$APPFILE")" ]; then
    die "$APPFILE already contains modifications."
fi

# Get application name.
APPNAME="$(cat "$APPDIR"/"$APPFILE" | sed -n 's|^[ ]*name: \([a-zA-Z0-9_\-]\+\)$|\1|p' | head -n 1)"
APPFRIENDLYNAME="$(cat "$APPDIR"/"$APPFILE" | sed -n 's|^[ ]*friendly_name: \([ a-zA-Z0-9_\-]\+\)$|\1|p' | head -n 1)"

# Get current version.
CUR_VERSION="$(cat "$APPDIR"/"$APPFILE" | sed -n 's|.*- version: \([0-9.]\+\)$|\1|p' | head -n 1)"
CUR_VERSION_YY_MM="$(echo "$CUR_VERSION" | cut -d'.' -f1-2)"
CUR_VERSION_SEQ="$(echo "$CUR_VERSION" | cut -d'.' -f3)"

# Set the new version.
VERSION_YY_MM="$(date "+%y.%m")"
if [ "$CUR_VERSION_YY_MM" = "$VERSION_YY_MM" ]
then
    VERSION_SEQ="$(expr $CUR_VERSION_SEQ + 1)"
else
    VERSION_SEQ="1"
fi
VERSION="$VERSION_YY_MM.$VERSION_SEQ"
[ "$CUR_VERSION" != "$VERSION" ] || die "Failed to generate version."

echo "Current version: $CUR_VERSION"
echo "New version:     $VERSION"

# Generate the changelog.
CHANGELOG="$(mktemp)"
CHANGELOG_GITHUB="$(mktemp)"
echo "Changes in this release:" >> "$CHANGELOG_GITHUB"
echo "    - version: $VERSION" >> "$CHANGELOG"
echo "      date: $(date +%Y-%m-%d)" >> "$CHANGELOG"
echo "      changes:" >> "$CHANGELOG"
while [ "$#" -gt 0 ]; do
    if echo "$1" | grep -q "^[0-9]\+:"; then
        LEVEL="$(echo "$1" | cut -d':' -f1)"
        CHANGE="$(echo "$1" | cut -d':' -f2- | sed -E "s/([^'])'([^'])/\1''\2/g")"
        echo "        - '$LEVEL:$CHANGE'" >> "$CHANGELOG"
        echo "$(printf '%0.s ' $(seq 1 $(expr 2 \* $LEVEL)))- $(echo "$CHANGE" | sed "s/''/'/" )" >> "$CHANGELOG_GITHUB"
    else
        echo "        - '$(echo $1 | sed -E "s/([^'])'([^'])/\1''\2/g")'" >> "$CHANGELOG"
        echo "  - $(echo "$1" | sed "s/''/'/" )" >> "$CHANGELOG_GITHUB"
    fi
    shift
done
#echo "Changelog:"
#echo "#############################################"
#cat "$CHANGELOG"
#echo "#############################################"

echo "Changelog GitHub:"
echo "#############################################"
cat "$CHANGELOG_GITHUB"
echo "#############################################"

# Add the release/changelog to appdefs.yml.
cp "$APPDIR"/"$APPFILE" "$APPFILE".bak
sed "/  changelog:/ r $CHANGELOG" "$APPFILE".bak > "$APPDIR"/"$APPFILE"
diff "$APPDIR"/"$APPFILE" "$APPFILE".bak > /dev/null 2>&1
if [ "$?" -ne 1 ]; then
    die "Failed to add the release to $APPFILE."
fi
rm "$APPFILE".bak
rm "$CHANGELOG"

# Commit the change.
if [ -d "$APPDIR"/.git ]; then
    echo "The following changes will be pushed to the git repository:"
    git -C "$APPDIR" --no-pager diff "$APPFILE"
    if promptyn 'Proceed'; then
        git -C "$APPDIR" add "$APPFILE" && \
        git -C "$APPDIR" commit -m "Added changelog for version $VERSION." && \
        git -C "$APPDIR" push origin master
        [ "$?" -eq 0 ] || die "Failed to commit changes."
    else
        exit 1
    fi
fi

# Add release to github.
if [ -d "$APPDIR"/.git ]; then
    if promptyn 'Is this a draft release'; then
        DRAFT="--draft"
    else
        DRAFT=""
    fi

    echo "Adding release to GitHub..."
    gh release create \
        v$VERSION \
        $DRAFT \
        --title "Version $VERSION" \
        --notes-file "$CHANGELOG_GITHUB"

    [ "$?" -eq 0 ] || die "Failed to add release to GitHub."
    rm "$CHANGELOG_GITHUB"
fi

# Update the unRAID template.
"$SCRIPTDIR"/render_templates.sh "$APPDIR" -u
if [ $? -eq 0 ]; then
    # Commit unRAID template.

    TEMPLATE_DIR="$(readlink -f "$APPDIR"/../docker-templates)"
    TEMPLATE_FILE=jlesage/"$APPNAME".xml

    [ -d "$TEMPLATE_DIR" ] || die "Directory not found: $TEMPLATE_DIR"
    [ -f "$TEMPLATE_DIR"/"$TEMPLATE_FILE" ] || die "File not found: $TEMPLATE_DIR/$TEMPLATE_FILE"

    # Make sure the template file is modified.
    if [ -z "$(git -C "$TEMPLATE_DIR" --no-pager diff "$TEMPLATE_FILE")" ]; then
        die "$TEMPLATE_FILE contains no modifications."
    fi

    # Make sure there is no pending changes.
    if [ -n "$(git -C "$TEMPLATE_DIR" diff --cached)" ]; then
        die "$TEMPLATE_DIR contains pending changes."
    fi

    echo "The following unRAID template changes will be commited:"
    git -C "$TEMPLATE_DIR" --no-pager diff "$TEMPLATE_FILE"
    if promptyn 'Proceed'; then
        git -C "$TEMPLATE_DIR" add "$TEMPLATE_FILE" && \
        git -C "$TEMPLATE_DIR" commit -m "Updated changelog of $APPFRIENDLYNAME." && \
        [ "$?" -eq 0 ] || die "Failed to commit changes."
    else
        exit 1
    fi
else
    die "Failed to update unRAID template."
fi

#TODO: Render templates
